name: Build Padavan NEWIFI3

on:
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công trên giao diện GitHub Actions
  push:
    branches:
      - master # Tự động chạy khi bạn push code lên nhánh master

jobs:
  build:
    runs-on: ubuntu-20.04 # Ubuntu 20.04 là môi trường ổn định nhất để biên dịch Toolchain Padavan
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v3

      - name: Khởi tạo môi trường biên dịch
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
            cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
            pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget \
            libc6-dev-i386

      - name: Tải Toolchain tiền biên dịch (MIPSLE)
        run: |
          cd toolchain-mipsel
          sh dl_toolchain.sh

      - name: Tiến hành dọn dẹp và Biên dịch ROM
        run: |
          # Sao chép cấu hình build.config từ thư mục gốc đè vào file mẫu của board và file đích .config
          cp -f build.config trunk/configs/templates/NEWIFI3.config
          cp -f build.config trunk/.config
          
          cd trunk
          ./clear_tree
          ./build_firmware_modify NEWIFI3

      - name: Đóng gói và Upload Firmware lên Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Padavan_NEWIFI3_Firmware
          path: trunk/images/*.trx
